name: Recompile APK

on:
  push:
    branches:
      - main

jobs:
  recompile:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Download Apktool
        run: |
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O apktool.jar
          echo -e '#!/bin/sh\njava -jar $(dirname "$0")/apktool.jar "$@"' > apktool
          chmod +x apktool
          sudo mv apktool apktool.jar /usr/local/bin/

      - name: Recompile APK
        run: |
          cd "$(find . -type d -name '1MB_1.0_apkcombo.com')" || exit 1
          apktool b . -o ../1MB_1.0_recompiled.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: recompiled-apk
          path: 1MB_1.0_recompiled.apk
