name: Recompile APK

on:
  push:
    branches:
      - main

jobs:
  recompile:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Download Apktool
        run: |
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O apktool.jar
          echo -e '#!/bin/sh\njava -jar $(dirname "$0")/apktool.jar "$@"' > apktool
          chmod +x apktool
          sudo mv apktool apktool.jar /usr/local/bin/

      - name: Detect APK folder name
        id: detect
        run: |
          folder_name=$(find . -maxdepth 1 -type d ! -name '.' | tail -n1 | sed 's|./||')
          echo "folder_name=$folder_name" >> $GITHUB_OUTPUT
          echo "output_apk=${folder_name}_recompiled.apk" >> $GITHUB_OUTPUT

      - name: Recompile APK
        run: |
          mkdir -p output
          cd "${{ steps.detect.outputs.folder_name }}" || exit 1
          apktool b . -o "../output/${{ steps.detect.outputs.output_apk }}"

      - name: Create recompile_done.flag
        run: |
          echo "done" > recompile_done.flag

      - name: Push APK and flag to repo
        run: |
          git config user.name "ATHENA-Bot"
          git config user.email "athena@bot.com"
          git add output/
          git add recompile_done.flag
          git commit -m "chore: recompiled APK + flag"
          git push origin main
