name: Recompile APK

on:
  push:
    branches:
      - main

jobs:
  recompile:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Download Apktool
        run: |
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O apktool.jar
          echo -e '#!/bin/sh\njava -jar $(dirname "$0")/apktool.jar "$@"' > apktool
          chmod +x apktool
          sudo mv apktool apktool.jar /usr/local/bin/

      - name: Download apksigner
        run: |
          mkdir -p $HOME/android-sdk/build-tools/34.0.0
          wget https://dl.google.com/android/repository/build-tools_r34.0.0-linux.zip
          unzip build-tools_r34.0.0-linux.zip -d $HOME/android-sdk/build-tools
          echo "$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Detect APK folder name
        id: detect
        run: |
          folder_name=$(find . -maxdepth 1 -type d ! -name '.' ! -name '.git' ! -name '.github' ! -path '*/\.*' | head -n1 | sed 's|./||')
          if [ -z "$folder_name" ]; then
            echo "No valid folder found for recompilation."
            exit 1
          fi
          echo "Detected folder: $folder_name"
          echo "folder_name=$folder_name" >> $GITHUB_OUTPUT
          echo "output_apk=${folder_name}_recompiled.apk" >> $GITHUB_OUTPUT
          echo "signed_apk=signed-${folder_name}_recompiled.apk" >> $GITHUB_OUTPUT

      - name: Check if folder has apktool.yml
        id: check_apktool
        run: |
          folder="${{ steps.detect.outputs.folder_name }}"
          if [ -f "$folder/apktool.yml" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Debug folder contents
        run: |
          folder="${{ steps.detect.outputs.folder_name }}"
          echo "Listing contents of $folder:"
          ls -al "$folder"

      - name: Recompile APK
        if: steps.check_apktool.outputs.exists == 'true'
        run: |
          mkdir -p output
          cd "${{ steps.detect.outputs.folder_name }}"
          apktool b . -o "../output/${{ steps.detect.outputs.output_apk }}"
          echo "Recompilation complete."

      - name: Decode keystore
        if: steps.check_apktool.outputs.exists == 'true'
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > athena-keystore.jks

      - name: Sign APK
        if: steps.check_apktool.outputs.exists == 'true'
        run: |
          apksigner sign \
            --ks athena-keystore.jks \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out "output/${{ steps.detect.outputs.signed_apk }}" \
            "output/${{ steps.detect.outputs.output_apk }}"
          echo "APK signing complete."

      - name: Create recompile_done.flag
        if: steps.check_apktool.outputs.exists == 'true'
        run: echo "done" > recompile_done.flag

      - name: Push signed APK and flag to repo
        if: steps.check_apktool.outputs.exists == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "ATHENA-Bot"
          git config user.email "athena@bot.com"
          git add output/${{ steps.detect.outputs.signed_apk }} recompile_done.flag || echo "Nothing to add"
          git commit -m "chore: signed recompiled APK + flag" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
