name: Recompile APK

on:
  push:
    branches:
      - main

jobs:
  recompile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Download Apktool
      run: |
        curl -L -o apktool.jar https://github.com/iBotPeaches/Apktool/releases/download/v2.7.0/apktool_2.7.0.jar

    - name: Recompile APK
      run: |
        java -jar apktool.jar b decompiled_apk_folder -o recompiled_output.apk

    - name: Upload recompiled APK
      uses: actions/upload-artifact@v2
      with:
        name: recompiled-apk
        path: recompiled_output.apk
